site_name: AstroPilot

nav:
  - Home: index.md
  - Installation: install.md
  - API Reference:
      - Astropilot: api_astropilot.md
      

theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            docstring_style: google
            annotations_path: brief
            show_signature: true
            separate_signature: true
            show_root_toc_entry: false
            show_root_members_full_path: true
            merge_init_into_class: true
            filters:
              - "!^_"

extra_css:
  - css/mkdocstrings.css
