site_name: AstroPilot

nav:
  - Home: index.md
  - Installation: install.md
  - Get started: get_started.md
  - Prompts: prompts.md
  - API Reference:
    - Astropilot: api_astropilot.md
    - Classes: api_classes.md
    - Paper: api_paper.md

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # show_source: false
            docstring_style: google
            annotations_path: brief
            show_signature: true
            separate_signature: true
            show_root_toc_entry: false
            show_root_members_full_path: true
            merge_init_into_class: true
            show_signature_annotations: true
            filters:
              - "!^_"

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences